pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                script {
                    // Change into the ADDA directory
                    dir('ADDA') {
                        // Run Maven build commands using Maven Wrapper
                        bat "mvn clean install"
                    }
                }
            }
        }
    }

    post {
        failure {
            echo "Build failed! See above for details."
        }
    }
}
