pipeline {
    agent any

    environment {
        MVN_HOME = 'C:\\Program Files\\apache-maven-3.9.5'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                script {
                    // Setting the PATH to include Maven
                    def mavenHome = tool name: 'Maven', type: 'maven'
                    env.PATH = "${mavenHome}\\bin;${env.PATH}"

                    // Running Maven build commands
                    bat "mvn clean install"
                }
            }
        }
    }

    post {
        failure {
            echo "Build failed! See above for details."
        }
    }
}
